version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  main_job:
    executor:
      name: node/default
      tag: "18.19"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: ./node_modules/.bin/lerna run compile
          name: compilation
      - run:
          command: ./node_modules/.bin/lerna run lint
          name: linter
      - run:
          command: ./node_modules/.bin/lerna run test
          name: test
      - store_test_results:
          path: ./test_results

workflows:
  main:
    jobs:
      - main_job
